export default [
  { name: 'Chroma 2 Case', def_index: 4089 },
  { name: 'Chroma 3 Case', def_index: 4233 },
  { name: 'Chroma Case', def_index: 4061 },
  { name: 'Clutch Case', def_index: 4471 },
  { name: 'CS20 Case', def_index: 4669 },
  { name: 'Danger Zone Case', def_index: 4548 },
  { name: 'Dreams & Nightmares Case', def_index: 4818 },
  { name: 'eSports 2013 Case', def_index: 4002 },
  { name: 'eSports 2013 Winter Case', def_index: 4005 },
  { name: 'eSports 2014 Summer Case', def_index: 4019 },
  { name: 'Falchion Case', def_index: 4091 },
  { name: 'Fracture Case', def_index: 4698 },
  { name: 'Gamma 2 Case', def_index: 4281 },
  { name: 'Gamma Case', def_index: 4236 },
  { name: 'Glove Case', def_index: 4288 },
  { name: 'Horizon Case', def_index: 4482 },
  { name: 'Huntsman Weapon Case', def_index: 4017 },
  { name: 'Operation Bravo Case', def_index: 4003 },
  { name: 'Operation Breakout Case', def_index: 4018 },
  { name: 'Operation Broken Fang Case', def_index: 4717 },
  { name: 'Operation Hydra Case', def_index: 4352 },
  { name: 'Operation Pheonix Weapon Case', def_index: 4011 },
  { name: 'Operation Riptide Case', def_index: 4790 },
  { name: 'Operation Vanguard Weapon Case', def_index: 4029 },
  { name: 'Operation Wildfire Case', def_index: 4187 },
  { name: 'Prisma 2 Case', def_index: 4695 },
  { name: 'Prisma Case', def_index: 4598 },
  { name: 'Recoil Case', def_index: 4846 },
  { name: 'Revolution Case', def_index: 4880 },
  { name: 'Revolver Case', def_index: 4186 },
  { name: 'Shadow Case', def_index: 4138 },
  { name: 'Shattered Web Case', def_index: 4620 },
  { name: 'Snakebite Case', def_index: 4747 },
  { name: 'Spectrum 2 Case', def_index: 4403 },
  { name: 'Spectrum Case', def_index: 4351 },
  { name: 'Weapon Case', def_index: 4001 },
  { name: 'Weapon Case 2', def_index: 4004 },
  { name: 'Weapon Case 3', def_index: 4010 },
  { name: 'Winter Offensive Weapon Case', def_index: 4009 },
];
